---
title: "NYC Airbnb Data Assignment"
author: "Data Mine’R’s"
date: "8/26/2020"
output:
  html_document:
    highlight: tango
    theme: united
    toc: yes
    toc_depth: 3
    toc_float:
      collapsed: no
  pdf_document:
    toc: yes
    toc_depth: '3'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<style>
#TOC {
 color: 
 font-family: Calibri;
 background-color:
 border-color: darkred;
}
#header {
 color: darkred;
 font-family: Calibri;
 background-color:
}
body {
 font-family: Calibri;
 }
 
</style>

## 1. Introduction
### 1.1. What is Airbnb?

Airbnb is an online marketplace since 2008, which connects people who want to rent their homes with people who are looking for accommodations in a particular location. It covers more than 81,000 cities and 191 countries worldwide. The company ,which is based in San Francisco, Califarnia, does not own any of the property listings, but it receives commissions from each booking like a broker. The name "Airbnb" comes from “air mattress Bed and Breakfast.” The Airbnb logo is called the Bélo, which is a short version for saying ‘Belong Anywhere’. Airbnb hosts list many different kinds of properties such as private rooms, apartments, shared rooms, houseboats, entire houses, etc. 

### 1.2. Airbnb Dataset

This dataset describes the listing activity and metrics in NYC for 2019. It includes all the necessary information in order to find out more about hosts, prices, geographical availability, and necessary information to make predictions and draw conclusions for NYC. The explanation of the variables in our data, which consists of 16 columns and 48,895 rows, will be made in the next part. The data used in this assignment is called **New York City Airbnb Open Data** which is downloaded from [Kaggle](https://www.kaggle.com/dgomonov/new-york-city-airbnb-open-data). This public dataset is a part of Airbnb, and the original source can be found on this [website](http://insideairbnb.com/).

### 1.3. Objectives

In this assignment, we will perform an exploratory data analysis(EDA) in order to investigate each of the variables and also come up with a conclusion for the relationship between variables. The main purpose is to identify which variables affect the price mostly, and include a regression model with price as a response variable. In addition to these, we will explore which neighborhood groups and room types are the most popular ones among the guests, and which hosts are the most preferred ones. The processes during the assignment can be listes as below:<br>

 1. Data Preprocessing
 2. Data Manipulation
 3. Data Visualization
 4. Interactive Shiny App
 5. Forecasting

## 2. Data Explanation

### 2.1. Variables

This dataset contains 16 features about Airbnb listings within New York City. Below are the features with their descriptions:<br>

 1. `id`: Listing ID (numeric variable)
 2. `name`: Listing Title (categorical variable) 
 3. `host_id`: ID of Host (numeric variable)
 4. `host_name`: Name of Host (categorical Variable)<br>
 5. `neighbourhood_group`: Neighbourhood group that contains listing (categorical variable)
 6. `neighbourhood`: Neighbourhood group that contains listing (categorical variable)
 7. `latitude`: Latitude of listing (numeric variable)
 8. `longitude`: Longitude of listing (numeric variable)
 9. `room_type`: Type of the offered property (categorical variable)
 10. `price`: Price per night in USD (numeric variable)
 11. `minimum_nights`: Minimum number of nights required to book listing (numeric variable)
 12. `number_of_reviews`: Total number of reviews that listing has (numeric variable)
 13. `last_review`: Last rent date of the listing (date variable)
 14. `reviews_per_month`: Total number of reviews divided by the number of months that the listing is active (numeric variable)
 15. `calculated_host_listings_count`: Amount of listing per host (numeric variable)
 16. `availability_365`: Number of days per year the listing is active (numeric variable)
 
### 2.2. Used Libraries

We have used several packages during the analysis of the historical data of Airbnb in NYC in order to make data manipulation and visualization. The list of packages used in this assignment can be seen below:<br>

 1. tidyverse
 2. lubridate
 3. tinytex
 4. wordcloud
 5. shiny
 6. knitr
 7. data.table
 
**Buraya kullanacağımız diğer paketleri de ekleriz. Library komutu ile paketleri yüklediğimiz ve datayı import ettiğimiz kodu koyarız. glimpse() ile dataya bakarız**

### 2.3. Dublicate and Missing Data

**Dublicate ve NA var mı diye kontrol ettiğimiz kodu ekleriz. **

###  2.4. Summary of Data

**summary ile dataya baktıgımız kodu koyarız.**

## 3. Analysis
